[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "flask-debugtoolbar"
version = "0.6"
dependencies = [
    "flask",
    "requests"
]

[tool.setuptools]
py-modules = ["flask_debugtoolbar"]
